name: Branch build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Persist cache
        uses: actions/cache@v6
        id: local-dot-cache
        with:
          path: .cache
          key: ${{ runner.os }}-local-dot-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Setup
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test
      - name: Package version
        run: pnpm generate-version
      - name: Package bundle
        run: pnpm build
      - name: Package information
        run: pnpm -r publish --dry-run --no-git-checks
